### ISSUE TITLE
Критическая ошибка

### ISSUE THREAD

**Issue by 3peekawOwD** [Mrsasha45op/lzt-api#1]
Критическая ошибка на Glitch
```
(node:2458) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!

[0712/111041.661515:FATAL:zygote_host_impl_linux.cc(116)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux/suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.

#0 0x556e5a1e1399 base::debug::CollectStackTrace()

#1 0x556e5a1422a3 base::debug::StackTrace::StackTrace()

#2 0x556e5a153c95 logging::LogMessage::~LogMessage()

#3 0x556e5ba3040e service_manager::ZygoteHostImpl::Init()

#4 0x556e59d0c060 content::ContentMainRunnerImpl::Initialize()

#5 0x556e59d6d5e7 service_manager::Main()

#6 0x556e59d0a631 content::ContentMain()

#7 0x556e59d6c80d headless::(anonymous namespace)::RunContentMain()

#8 0x556e59d6c50c headless::HeadlessShellMain()

#9 0x556e577605a7 ChromeMain

#10 0x7f0420f2e830 __libc_start_main

#11 0x556e577603ea _start

Received signal 6

#0 0x556e5a1e1399 base::debug::CollectStackTrace()

#1 0x556e5a1422a3 base::debug::StackTrace::StackTrace()

#2 0x556e5a1e0f35 base::debug::(anonymous namespace)::StackDumpSignalHandler()

#3 0x7f04274c4390 (/lib/x86_64-linux-gnu/libpthread-2.23.so+0x1138f)

#4 0x7f0420f43428 gsignal

#5 0x7f0420f4502a abort

#6 0x556e5a1dfe95 base::debug::BreakDebugger()

#7 0x556e5a154132 logging::LogMessage::~LogMessage()

#8 0x556e5ba3040e service_manager::ZygoteHostImpl::Init()

#9 0x556e59d0c060 content::ContentMainRunnerImpl::Initialize()

#10 0x556e59d6d5e7 service_manager::Main()

#11 0x556e59d0a631 content::ContentMain()

#12 0x556e59d6c80d headless::(anonymous namespace)::RunContentMain()

#13 0x556e59d6c50c headless::HeadlessShellMain()

#14 0x556e577605a7 ChromeMain

#15 0x7f0420f2e830 __libc_start_main

#16 0x556e577603ea _start

  r8: 0000000000000000  r9: 0000000000000000 r10: 0000000000000008 r11: 0000000000000206

 r12: 00007ffde49a7018 r13: 00007ffde49a5ff0 r14: 00007ffde49a7020 r15: aaaaaaaaaaaaaaaa

  di: 00000000000009b4  si: 00000000000009b4  bp: 00007ffde49a5fa0  bx: 00007ffde49a6014

  dx: 0000000000000006  ax: 0000000000000000  cx: 00007f0420f43428  sp: 00007ffde49a5e68

  ip: 00007f0420f43428 efl: 0000000000000206 cgf: aaaa000000000033 erf: 0000000000000000

 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000

[end of stack trace]

Calling _exit(1). Core file will not be generated.

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/rbd/pnpm-volume/f12642cf-7f1f-43f8-8ab3-119535b36db7/node_modules/.registry.npmjs.org/puppeteer/5.0.0/node_modules/puppeteer/lib/cjs/node/BrowserRunner.js:193:20)

    at Interface.<anonymous> (/rbd/pnpm-volume/f12642cf-7f1f-43f8-8ab3-119535b36db7/node_modules/.registry.npmjs.org/puppeteer/5.0.0/node_modules/puppeteer/lib/cjs/node/BrowserRunner.js:183:65)

    at Interface.emit (events.js:201:15)

    at Interface.close (readline.js:401:8)

    at Socket.onend (readline.js:178:10)

    at Socket.emit (events.js:201:15)

    at endReadableNT (_stream_readable.js:1130:12)

    at processTicksAndRejections (internal/process/task_queues.js:83:17)

(node:2458) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

(node:2458) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Mrsasha45op** [comment]
**If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.**
Читать ошибки - полезно
